
[common]
# The list of setup scripts that will run before the application commands.
setup_scripts = [
    "echo 'download tomcat'"
]

# The number of workers used to run the application commands in parallel.
# Default is 5.
workers = 5

[applications]

  # Each application should have steps and a command.  The steps are the commands to execute when the
  # program is called. The steps will be run serially, however each application will be setup in parallel.
  # The command block is the command that will be written into the Procfile when everything has been run.
  # To ignore a configured application you can comment it out or set enabled to false.

  [applications.member]
  steps = [
    "sleep 2"
  ]
  command = "java -jar downloads/member-service/app.jar server downloads/member-service/config.yml"

  [applications.employer]
  steps = [
    "sleep 1"
  ]
  command = "java -jar downloads/employer-graph-service/app.jar server downloads/employer-graph-service/config.yml"

  [applications.recommandation]
  steps = [
    "echo 'recommandation'"
  ]
  command = "java -jar downloads/recommandation-service/app.jar server downloads/recommandation-service/config.yml"
  enabled = true

  [applications.event_audit]
  steps = [
    "echo 'event audit'"
  ]
  command = "java -jar downloads/event-audit-service/app.jar server downloads/event-audit-service/config.yml"
  enabled = false
